version: 1.0.{build}
environment:
    nodejs_version: "12"

init:
- ps: Install-Product node $env:nodejs_version x64
install:
- cmd: npm config set msvs_version 2015
build_script:
- cmd: restore-nuget-packages.bat
- cmd: npm install
test_script:
- cmd: npm test
