/* Copyright 2017 Cinegy GmbH.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.

  The version of Cinecoder for these headers should be: 3.30.18.13164
*/

import "Unknwn.idl";

#include "Cinecoder_Version.h"

#include "interfaces/cc_typedefs.idl"

/////////////////////////////////////////////////////////////////////////////////////
cpp_quote("#ifdef _WIN32")
cpp_quote("#define _DSO_VISIBLE_")
cpp_quote("#else")
cpp_quote("#define _DSO_VISIBLE_ __attribute__ ((visibility(\"default\")))")
cpp_quote("#endif")
cpp_quote("STDAPI_(CC_VERSION_INFO)  Cinecoder_GetVersion        ()                   _DSO_VISIBLE_;")
cpp_quote("STDAPI                    Cinecoder_CreateClassFactory(ICC_ClassFactory**) _DSO_VISIBLE_;")
cpp_quote("STDAPI                    Cinecoder_SetErrorHandler   (ICC_ErrorHandler *pHandler, ICC_ErrorHandler **pOldHandler = 0) _DSO_VISIBLE_;")
cpp_quote("STDAPI                    Cinecoder_GetErrorHandler   (ICC_ErrorHandler**pHandler) _DSO_VISIBLE_;")
cpp_quote("STDAPI_(LPCSTR)           Cinecoder_GetErrorString    (HRESULT code)       _DSO_VISIBLE_;")
cpp_quote("STDAPI                    Cinecoder_ConvertProfile    (LPCSTR OldProfile, LPTSTR NewProfileBuff, int NewProfileBuffLen, CC_BOOL bScheme) _DSO_VISIBLE_;")
cpp_quote("#undef _DSO_VISIBLE_")

#include "interfaces/cc_factory.idl"
#include "interfaces/cc_baseclasses.idl"
#include "interfaces/cc_fileio.idl"
#include "interfaces/cc_elementary.idl"
#include "interfaces/cc_devices.idl"
#include "interfaces/cc_collection.idl"

#include "interfaces/cc_audio.idl"
#include "interfaces/cc_audio_mpeg.idl"
#include "interfaces/cc_audio_aes3.idl"
#include "interfaces/cc_audio_aac.idl"
#include "interfaces/cc_audio_lpcm.idl"
#include "interfaces/cc_audio_ac3.idl"
#include "interfaces/cc_audio_wav.idl"

#include "interfaces/cc_video.idl"
#include "interfaces/cc_video_mpeg.idl"
#include "interfaces/cc_video_d10.idl"
#include "interfaces/cc_video_xdcam.idl"
#include "interfaces/cc_video_h264.idl"
#include "interfaces/cc_video_hevc.idl"
#include "interfaces/cc_video_avci.idl"
#include "interfaces/cc_video_mpeg4.idl"
#include "interfaces/cc_video_j2k.idl"
#include "interfaces/cc_video_sonyraw.idl"
#include "interfaces/cc_video_prores.idl"
#include "interfaces/cc_video_daniel.idl"
#include "interfaces/cc_video_y4m.idl"

#include "interfaces/systems/cc_systems.idl"
#include "interfaces/systems/cc_mp4_mux.idl"
#include "interfaces/systems/cc_hls_mux.idl"
#include "interfaces/systems/cc_scte35.idl"

//#include "interfaces/cc_media_cleaner.idl"
#include "interfaces/cc_media_reader.idl"

//////////////////////////////////////////////////////////////////////
// classes
//////////////////////////////////////////////////////////////////////

[uuid(80011100-0315-11dc-a983-0018f3fe411b), helpstring("Cinecoder(r) Library"), version(CINECODER_VERSION_TLB)]
library Cinecoder
{
  [uuid(00000000-be08-11dc-aa88-005056c00008)]
  coclass CinecoderLibrary
  {
    [default]
    interface ICC_ClassFactory;
  }

  struct	tagPOINT;
  
  enum      CC_PERIOD_FLAGS;
  struct    CC_VERSION_INFO;
  struct    CC_ADD_VIDEO_FRAME_PARAMS;

  enum      CC_FRAME_TYPE;
  enum      CC_MPG_FRAME_FLAGS;
  enum      CC_XDCAM_MODE;

  enum      SCTE35_SPLICE_COMMAND_TYPE;
  struct    SCTE35_SPLICE_NULL_COMMAND_DESCR;
  struct    SCTE35_SPLICE_INSERT_COMMAND_DESCR;

  interface ICC_Schema;
  interface ICC_ErrorHandler;

  interface ICC_BufferAllocator;
  interface ICC_Breakable;
  interface ICC_DataReadyCallback;
  interface ICC_ByteStreamCallback;
  interface ICC_Decoder;
  interface ICC_DemultiplexedDataCallback;
  interface ICC_InitialTimeCodeProp;
  interface ICC_StreamClockReferenceProp;
  interface ICC_ElementarySplitter;
  interface ICC_DebugDumpIncomingDataToFile;
  interface ICC_PsnrCalculationProp;
  interface ICC_MultiplexedDataDescr;

  interface ICC_StreamPositionProp;
  interface ICC_DataWriter;
  interface ICC_DataWriterEx;

  interface ICC_TimeBaseProp;
  interface ICC_BitRateProp;

  interface ICC_ThreadsCountProp;
  interface ICC_ThreadsAffinityProp;
  interface ICC_ThreadsPriorityProp;

  interface ICC_ProcessDataPolicyProp;
  interface ICC_ExecutiveDeviceMaskProp;
  interface ICC_AddUserDataCtrl;

  // The cinecoder "video" interfaces
  interface ICC_VideoDescr;
  interface ICC_MpegVideoStreamInfo;
  interface ICC_VideoFrameInfo;
  interface ICC_MpegVideoFrameInfo;
  interface ICC_VideoFrameQualityInfo;
  interface ICC_VideoDataHandler;
  interface ICC_VideoProducer;
  interface ICC_VideoConsumer;
  interface ICC_VideoConsumerExt;
  interface ICC_VideoConsumerExtAsync;
  interface ICC_VideoRescaleConsumer;

  // The ICC_Collection interfaces
  interface ICC_Collection;
  interface ICC_ReadOnlyCollection;
  interface ICC_CollectionHandler;
  interface ICC_CollectionChanged;
  interface ICC_CollectionFilter;

  // The mp4 additional interfaces
  interface ICC_MP4Fragment;
  interface ICC_MP4InitFragment;
  
  interface ICC_File;
  interface ICC_InputFile;
  interface ICC_OutputFile;

  [uuid(80011101-0315-11dc-a983-0018f3fe411b)]
  coclass CC_MpegVideoEncoderSettings
  {
    interface ICC_MpegVideoEncoderSettings;
  };

  [uuid(80011102-0315-11dc-a983-0018f3fe411b)]
  coclass CC_MpegVideoEncoder
  {
    [default]
    interface ICC_MpegVideoEncoder;
    interface ICC_VideoEncoder;
    interface ICC_Encoder;
    interface ICC_VideoConsumer;
    interface ICC_VideoConsumerExt;
	interface ICC_ByteStreamProducer;
    interface ICC_StreamProcessor;
    interface ICC_InputBufferControl;
    interface ICC_ThreadsCountProp;
    interface ICC_ThreadsAffinityProp;
    interface ICC_ThreadsPriorityProp;
    interface ICC_TimeBaseProp;
    interface ICC_InitialTimeCodeProp;
    interface ICC_AddUserDataCtrl;
  };

  [uuid(eb953846-1fbc-408a-91f9-f7a8acda02d1)]
  coclass CC_MpegVideoEncoder2
  {
    [default]
    interface ICC_MpegVideoEncoder;
    interface ICC_VideoEncoder;
    interface ICC_Encoder;
    interface ICC_VideoConsumer;
    interface ICC_VideoConsumerExt;
	interface ICC_ByteStreamProducer;
    interface ICC_StreamProcessor;
    interface ICC_InputBufferControl;
    interface ICC_ThreadsCountProp;
    interface ICC_ThreadsAffinityProp;
    interface ICC_ThreadsPriorityProp;
    interface ICC_TimeBaseProp;
    interface ICC_InitialTimeCodeProp;
    interface ICC_AddUserDataCtrl;
  };

  [uuid(80011203-0315-11dc-a983-0018f3fe411b)]
  coclass CC_MpegVideoDecoder
  {
    [default]
    interface ICC_MpegVideoDecoder;
    interface ICC_VideoDecoder;
    interface ICC_StreamProcessor;
	interface ICC_ByteStreamConsumer;
    interface ICC_VideoProducer;
  };

  // An original CPU-based MPEG video decoder
  [uuid(a13ea19d-f813-4abd-ae8f-889e4f535c21)]
  coclass CC_MpegVideoDecoder0
  {
    [default]
    interface ICC_MpegVideoDecoder;
    interface ICC_VideoDecoder;
    interface ICC_StreamProcessor;
	interface ICC_ByteStreamConsumer;
    interface ICC_VideoProducer;
  };

  [uuid(475e4d15-7f66-4176-bc85-8c9c3805b4cd)]
  coclass CC_MpegVideoDecoder2
  {
    [default]
    interface ICC_MpegVideoDecoder;
    interface ICC_VideoDecoder;
    interface ICC_StreamProcessor;
	interface ICC_ByteStreamConsumer;
    interface ICC_VideoProducer;
  };

  [uuid(80011108-0315-11dc-a983-0018f3fe411b)]
  coclass CC_D10VideoEncoderSettings
  {
    interface ICC_D10VideoEncoderSettings;
  };

  [uuid(80011109-0315-11dc-a983-0018f3fe411b)]
  coclass CC_D10VideoEncoder
  {
    [default]
    interface ICC_D10VideoEncoder;
    interface ICC_StreamProcessor;
    interface ICC_VideoConsumer;
	interface ICC_ByteStreamProducer;
  };

  [uuid(b0effac6-56e3-42f1-8ff7-78f8f0fc4706)]
  coclass CC_MpegVideoSplitter
  {
    [default]
    interface ICC_MpegVideoSplitter;
	interface ICC_ByteStreamProducer;
	interface ICC_ByteStreamConsumer;
	interface ICC_StreamRecovery;
  };

  // The cinecoder "audio" interfaces
  interface ICC_AudioDescr;
  interface ICC_MpegAudioDescr;
  interface ICC_AudioProducer;
  interface ICC_AudioConsumer;
  interface ICC_MpegAudioDecoder;
  interface ICC_MpegAudioEncoder;
  interface ICC_MpegAudioEncoderSettings;

  [uuid(80011103-0315-11dc-a983-0018f3fe411b)]
  coclass CC_MpegAudioEncoderSettings
  {
    [default]
    interface ICC_MpegAudioEncoderSettings;
    interface ICC_ElementaryStreamInfo;
  };

  [uuid(80011104-0315-11dc-a983-0018f3fe411b)]
  coclass CC_MpegAudioEncoder
  {
    [default]
	interface ICC_MpegAudioEncoder;
	interface ICC_AudioEncoder;
    interface ICC_StreamProcessor;
	interface ICC_ByteStreamProducer;
    interface ICC_AudioConsumer;
	interface ICC_ThreadsAffinityProp;
	interface ICC_ThreadsPriorityProp;
  };

  [uuid(fde7ec62-213f-4dc7-af34-c9b471472fc5)]
  coclass CC_MpegAudioEncoderOld
  {
    [default]
	interface ICC_MpegAudioEncoder;
	interface ICC_AudioEncoder;
    interface ICC_StreamProcessor;
	interface ICC_ByteStreamProducer;
    interface ICC_AudioConsumer;
	interface ICC_ThreadsAffinityProp;
	interface ICC_ThreadsPriorityProp;
  };

  [uuid(80011105-0315-11dc-a983-0018f3fe411b)]
  coclass CC_Aes3AudioEncoderSettings
  {
    [default]
    interface ICC_Aes3AudioEncoderSettings;
    interface ICC_ElementaryStreamInfo;
  };

  [uuid(80011106-0315-11dc-a983-0018f3fe411b)]
  coclass CC_Aes3AudioEncoder
  {
    [default]
	interface ICC_Aes3AudioEncoder;
	interface ICC_AudioEncoder;
    interface ICC_StreamProcessor;
	interface ICC_ByteStreamProducer;
    interface ICC_AudioConsumer;
    interface ICC_AudioStreamInfo;
	interface ICC_ThreadsAffinityProp;
	interface ICC_ThreadsPriorityProp;
  };

  [uuid(80011204-0315-11dc-a983-0018f3fe411b)]
  coclass CC_MpegAudioDecoder
  {
    [default]
	interface ICC_MpegAudioDecoder;
    interface ICC_StreamProcessor;
    interface ICC_AudioProducer;
    interface ICC_AudioStreamInfo;
	interface ICC_AudioDecoder;
  };

  [uuid(516b31da-edff-4c2f-be28-9d49bf21a75f)]
  coclass CC_MpegAudioDecoderOld
  {
    [default]
	interface ICC_MpegAudioDecoder;
    interface ICC_StreamProcessor;
    interface ICC_AudioProducer;
    interface ICC_AudioStreamInfo;
	interface ICC_AudioDecoder;
  };

  [uuid(fcc7a5e3-3627-4a13-8f3f-f36841e258c7)]
  coclass CC_MpegAudioSplitter
  {
    [default]
	interface ICC_MpegAudioSplitter;
	interface ICC_AudioSplitter;
    interface ICC_Splitter;
    interface ICC_Decoder;
	interface ICC_ByteStreamConsumer;
    interface ICC_ByteStreamProducer;
    interface ICC_StreamProcessor;
  };

  [uuid(80011205-0315-11dc-a983-0018f3fe411b)]
  coclass CC_Aes3AudioDecoder
  {
    [default]
	interface ICC_Aes3AudioDecoder;
    interface ICC_StreamProcessor;
    interface ICC_AudioProducer;
    interface ICC_AudioStreamInfo;
	interface ICC_AudioDecoder;
  };

  // Multiplexer API ----------------------------------------
  
  [uuid(80011402-0315-11dc-a983-0018f3fe411b)]
  coclass CC_ProgramStreamMultiplexer
  {
    [default]
    interface ICC_Multiplexer;
    interface ICC_StreamProcessor;
    interface ICC_ByteStreamProducer;
	interface ICC_ThreadsAffinityProp;
	interface ICC_ThreadsPriorityProp;
  };
  [uuid(80011403-0315-11dc-a983-0018f3fe411b)]
  coclass CC_TransportStreamMultiplexer
  {
    [default]
    interface ICC_Multiplexer;
    interface ICC_StreamProcessor;
    interface ICC_ByteStreamProducer;
	interface ICC_ThreadsAffinityProp;
	interface ICC_ThreadsPriorityProp;
  };
  [uuid(80011404-0315-11dc-a983-0018f3fe411b)]
  coclass CC_HDV1_Multiplexer
  {
    [default]
    interface ICC_Multiplexer;
    interface ICC_StreamProcessor;
    interface ICC_ByteStreamProducer;
	interface ICC_ThreadsAffinityProp;
	interface ICC_ThreadsPriorityProp;
  };
  [uuid(80011405-0315-11dc-a983-0018f3fe411b)]
  coclass CC_HDV2_Multiplexer
  {
    [default]
    interface ICC_Multiplexer;
    interface ICC_StreamProcessor;
    interface ICC_ByteStreamProducer;
	interface ICC_ThreadsAffinityProp;
	interface ICC_ThreadsPriorityProp;
  };

  [uuid(80011302-0315-11dc-a983-0018f3fe411b)]
  coclass CC_ProgramMultiplexerSettings
  {
    [default]
    interface ICC_ProgramMultiplexerSettings;
    interface ICC_BaseMultiplexerSettings;
  };
  [uuid(80011303-0315-11dc-a983-0018f3fe411b)]
  coclass CC_TransportMultiplexerSettings
  {
    [default]
    interface ICC_TransportMultiplexerSettings;
    interface ICC_BaseMultiplexerSettings;
  };

  [uuid(80011304-0315-11dc-a983-0018f3fe411b)]
  coclass CC_MuxPinSettings
  {
  	interface ICC_BaseMultiplexerPinSettings;
    interface ICC_SystemMuxerPinSettings;
    interface ICC_ProgramMuxerPinSettings;
    interface ICC_TransportMuxerPinSettings;
  };
  [uuid(78360ef9-f2ce-4065-97b2-b74c65ab2513)]
  coclass CC_ProgramMuxerPinSettings
  {
    [default]
    interface ICC_ProgramMuxerPinSettings;
  };
  [uuid(f2af2b0e-5691-48f6-bc86-902df28edfb0)]
  coclass CC_TransportMuxerPinSettings
  {
    [default]
    interface ICC_TransportMuxerPinSettings;
  };

  [uuid(E828C337-9811-418d-B6E9-DDF40B91988D)]
  coclass CC_SystemsDescriptionManager
  {
    interface ICC_SystemDescriptorsManager;
  };

  [uuid(80011500-0315-11dc-a983-0018f3fe411b)]
  coclass CC_MpegDemultiplexer
  {
    [default]
    interface ICC_Demultiplexer;
    interface ICC_StreamProcessor;
  };

  [uuid(80011502-0315-11dc-a983-0018f3fe411b)]
  coclass CC_ProgramStreamDemultiplexer
  {
    [default]
    interface ICC_Demultiplexer;
    interface ICC_StreamProcessor;
  };

  [uuid(80011503-0315-11dc-a983-0018f3fe411b)]
  coclass CC_TransportStreamDemultiplexer
  {
    [default]
    interface ICC_Demultiplexer;
    interface ICC_StreamProcessor;
  };

  [uuid(80011601-0315-11dc-a983-0018f3fe411b)]
  coclass CC_H264VideoDecoder
  {
    [default]
    interface ICC_H264VideoDecoder;
    interface ICC_VideoDecoder;
    interface ICC_VideoProducer;
    interface ICC_ByteStreamConsumer;
    interface ICC_ByteStreamCallback;
    interface ICC_StreamProcessor;
    interface ICC_Breakable;
    interface ICC_TimeBaseProp;
  };

  // An original CPU-based H264 video decoder
  [uuid(24f7109a-d910-411c-9630-de39efb028b3)]
  coclass CC_H264VideoDecoder0
  {
    [default]
    interface ICC_H264VideoDecoder;
    interface ICC_VideoDecoder;
    interface ICC_VideoProducer;
    interface ICC_ByteStreamConsumer;
    interface ICC_ByteStreamCallback;
    interface ICC_StreamProcessor;
    interface ICC_Breakable;
    interface ICC_TimeBaseProp;
  };


  [uuid(80011602-0315-11dc-a983-0018f3fe411b)]
  coclass CC_AVC1VideoDecoder
  {
    [default]
    interface ICC_AVC1VideoDecoder;
    interface ICC_VideoDecoder;
    interface ICC_VideoProducer;
    interface ICC_ByteStreamConsumer;
    interface ICC_ByteStreamCallback;
    interface ICC_StreamProcessor;
    interface ICC_Breakable;
    interface ICC_TimeBaseProp;
  };

  // An original CPU-based AVC1 video decoder
  [uuid(c618cb66-1a6d-468a-b7bf-a9c4da6ba0c5)]
  coclass CC_AVC1VideoDecoder0
  {
    [default]
    interface ICC_AVC1VideoDecoder;
    interface ICC_VideoDecoder;
    interface ICC_VideoProducer;
    interface ICC_ByteStreamConsumer;
    interface ICC_ByteStreamCallback;
    interface ICC_StreamProcessor;
    interface ICC_Breakable;
    interface ICC_TimeBaseProp;
  };

  /// There's some help about H.264 Video Encoder
  [uuid(80011603-0315-11dc-a983-0018f3fe411b)]
  coclass CC_H264VideoEncoder
  {
    [default]
    interface ICC_H264VideoEncoder;
    interface ICC_VideoEncoder;
    interface ICC_VideoConsumer;
    interface ICC_VideoConsumerExt;
    interface ICC_ByteStreamProducer;
    interface ICC_StreamProcessor;
    interface ICC_InputBufferControl;
    interface ICC_ThreadsCountProp;
    interface ICC_ThreadsAffinityProp;
    interface ICC_ThreadsPriorityProp;
    interface ICC_TimeBaseProp;
    interface ICC_AddUserDataCtrl;
  };

  [uuid(80011604-0315-11dc-a983-0018f3fe411b)]
  coclass CC_H264VideoEncoderSettings
  {
    [default]
    interface ICC_H264VideoEncoderSettings;
  };

  [uuid(839555ed-00c2-4081-9323-be34cd1bb495)]
  coclass CC_H264VideoSplitter
  {
    [default]
    interface ICC_H264VideoSplitter;
    interface ICC_Splitter;
    interface ICC_Transcoder;
	interface ICC_ByteStreamProducer;
	interface ICC_ByteStreamConsumer;
    interface ICC_StreamProcessor;
    interface ICC_TimeBaseProp;
  };

  interface CC_H264_PROFILE;
  interface CC_H264_ENTROPY_CODING_MODE;

  [uuid(df24d3d2-9fe6-4a81-af22-e502b69e508a)]
  coclass CC_MP4_Multiplexer
  {
    [default]
    interface ICC_MP4_Multiplexer;
    interface ICC_MP4Producer;
    interface ICC_Multiplexer;
    interface ICC_StreamProcessor;
    interface ICC_ByteStreamProducer;
	interface ICC_ThreadsAffinityProp;
	interface ICC_ThreadsPriorityProp;
  };

  [uuid(c8344888-ca73-4819-b947-41e3842fcc46)]
  coclass CC_MP4_MultiplexerSettings
  {
    [default]
    interface ICC_MP4_MultiplexerSettings;
  };

  [uuid(df24d3d3-9fe6-4a81-af22-e502b69e508a)]
  coclass CC_MOV_Multiplexer
  {
    [default]
    interface ICC_MP4_Multiplexer;
    interface ICC_MP4Producer;
    interface ICC_Multiplexer;
    interface ICC_StreamProcessor;
    interface ICC_ByteStreamProducer;
	interface ICC_ThreadsAffinityProp;
	interface ICC_ThreadsPriorityProp;
  };

  [uuid(ec5dc6db-99f2-44f2-9657-eb629cfb705b)]
  coclass CC_MP4_MuxerPinSettings
  {
  	interface ICC_MP4_MuxerPinSettings;
    interface ICC_ElementaryStreamInfo;
  };

  [uuid(403de721-dade-4365-a587-589eb24215cf)]
  coclass CC_MP4_MuxerVideoPinSettings
  {
    interface ICC_MP4_MuxerVideoPinSettings;
    interface ICC_MP4_MuxerPinSettings;
    interface ICC_ElementaryStreamInfo;
  };

  [uuid(9954375D-1EFA-49A4-B2E4-C5A6C5352BA4)]
  coclass CC_MP4_MpegDashSettings
  {
    [default]
    interface ICC_MP4_MpegDashSettings;
  };

  [uuid(c19bf495-813d-4e19-9234-578e745cdd34)]
  coclass CC_AAC_AudioDecoder
  {
    [default]
	interface ICC_AAC_AudioDecoder;
	interface ICC_AudioDecoder;
    interface ICC_StreamProcessor;
	interface ICC_ByteStreamConsumer;
    interface ICC_AudioProducer;
    interface ICC_AudioStreamInfo;
	interface ICC_ThreadsAffinityProp;
	interface ICC_ThreadsPriorityProp;
  };

  [uuid(9bd13af0-ca9a-4909-8674-3d4dff42e425)]
  coclass CC_LATM_AAC_AudioDecoder
  {
    [default]
	interface ICC_LATM_AAC_AudioDecoder;
	interface ICC_AudioDecoder;
    interface ICC_StreamProcessor;
	interface ICC_ByteStreamConsumer;
    interface ICC_AudioProducer;
    interface ICC_AudioStreamInfo;
	interface ICC_ThreadsAffinityProp;
	interface ICC_ThreadsPriorityProp;
  };

  [uuid(c8064a72-1d96-47e0-8b20-72ae4ff0fe8d)]
  coclass CC_AAC_AudioEncoder
  {
    [default]
	interface ICC_AAC_AudioEncoder;
	interface ICC_AudioEncoder;
    interface ICC_StreamProcessor;
	interface ICC_ByteStreamProducer;
    interface ICC_AudioConsumer;
    interface ICC_AudioStreamInfo;
	interface ICC_ThreadsAffinityProp;
	interface ICC_ThreadsPriorityProp;
  };

  [uuid(f13e8488-4700-4e65-81d9-42de3ea85549)]
  coclass CC_AAC_AudioEncoderSettings
  {
    [default]
    interface ICC_AAC_AudioEncoderSettings;
    interface ICC_AAC_AudioStreamInfo;
  };

  [uuid(174b4d90-827b-48af-b57d-4fc12597b099)]
  coclass CC_AAC_AudioSplitter
  {
    [default]
	interface ICC_AAC_AudioSplitter;
	interface ICC_AudioSplitter;
    interface ICC_Splitter;
    interface ICC_Decoder;
	interface ICC_ByteStreamConsumer;
    interface ICC_ByteStreamProducer;
    interface ICC_StreamProcessor;
  };

  [uuid(ab977b61-58be-4d78-88cf-2769fbea46f9)]
  coclass CC_AC3_AudioDecoder
  {
    [default]
	interface ICC_AC3_AudioDecoder;
	interface ICC_AudioDecoder;
    interface ICC_StreamProcessor;
	interface ICC_ByteStreamConsumer;
    interface ICC_AudioProducer;
    interface ICC_AudioStreamInfo;
	interface ICC_ThreadsAffinityProp;
	interface ICC_ThreadsPriorityProp;
  };

  [uuid(86ab00cd-9c3f-405c-b164-8bb991d78744)]
  coclass CC_AC3_AudioSplitter
  {
    [default]
	interface ICC_AC3_AudioSplitter;
	interface ICC_AudioSplitter;
    interface ICC_Splitter;
    interface ICC_Decoder;
	interface ICC_ByteStreamConsumer;
    interface ICC_ByteStreamProducer;
    interface ICC_StreamProcessor;
  };

  [uuid(94a89306-b460-4670-9281-36b6431ef393)]
  coclass CC_AC3_AudioEncoder
  {
    [default]
	interface ICC_AC3_AudioEncoder;
	interface ICC_AudioEncoder;
    interface ICC_StreamProcessor;
	interface ICC_ByteStreamProducer;
    interface ICC_AudioConsumer;
    interface ICC_AudioStreamInfo;
	interface ICC_ThreadsAffinityProp;
	interface ICC_ThreadsPriorityProp;
  };

  [uuid(d066604f-7ccd-4e8d-8acd-01bcef8e99c3)]
  coclass CC_AC3_AudioEncoderSettings
  {
    [default]
    interface ICC_AC3_AudioEncoderSettings;
    interface ICC_AC3_AudioStreamInfo;
  };

  [uuid(4907c8e2-ef67-480e-b90d-bdba3f4a570a)]
  coclass CC_AVCIntraDecoder
  {
    [default]
    interface ICC_AVCIntraDecoder;
    interface ICC_StreamProcessor;
    interface ICC_VideoProducer;
	interface ICC_ByteStreamConsumer;
    interface ICC_ThreadsCountProp;
    interface ICC_ThreadsAffinityProp;
    interface ICC_ThreadsPriorityProp;
    interface ICC_TimeBaseProp;
  };

  [uuid(0cfa6ce8-0cd0-47d6-8e8e-3dc6b1e02e6f)]
  coclass CC_AVCIntraDecoder2
  {
    [default]
    interface ICC_AVCIntraDecoder;
    interface ICC_StreamProcessor;
    interface ICC_VideoProducer;
	interface ICC_ByteStreamConsumer;
    interface ICC_ThreadsCountProp;
    interface ICC_ThreadsAffinityProp;
    interface ICC_ThreadsPriorityProp;
    interface ICC_TimeBaseProp;
    interface ICC_ConcurrencyLevelProp;
  };

  [uuid(8ad378a7-88cb-4c1c-8150-d61e158a7326)]
  coclass CC_AVCIntraEncoder
  {
    [default]
    interface ICC_AVCIntraEncoder;
    interface ICC_StreamProcessor;
    interface ICC_VideoConsumer;
	interface ICC_ByteStreamProducer;
  };

  [uuid(2cd550f9-27ae-44c5-9b20-c46028c52632)]
  coclass CC_AVCIntraEncoderSettings
  {
    [default]
    interface ICC_AVCIntraEncoderSettings;
  };

  [uuid(5b97f2d2-2ae8-4c76-840a-661a0815d5f6)]
  coclass CC_Mpeg4VideoDecoder
  {
    [default]
    interface ICC_Mpeg4VideoDecoder;
    interface ICC_VideoDecoder;
    interface ICC_StreamProcessor;
	interface ICC_ByteStreamConsumer;
    interface ICC_VideoProducer;
  };

  [uuid(13397d8e-a4f7-4f67-b346-d61684553716)]
  coclass CC_MvxWriter
  {
    [default]
    interface ICC_IndexWriter;
    interface ICC_StreamProcessor;
	interface ICC_ByteStreamCallback;
	interface ICC_ByteStreamProducer;
	interface ICC_Breakable;
  };

  [uuid(152e6383-46fd-4c20-bee9-126dbc498fb5)]
  coclass CC_BluRay_PCM_AudioDecoder
  {
    [default]
	interface ICC_BluRay_PCM_AudioDecoder;
	interface ICC_AudioDecoder;
    interface ICC_StreamProcessor;
	interface ICC_ByteStreamConsumer;
    interface ICC_AudioProducer;
  };

  [uuid(c1d5d4aa-d523-45a2-b7fa-57bc99aec9ee)]
  coclass CC_LPCM_AudioEncoder
  {
    [default]
	interface ICC_LPCM_AudioEncoder;
	interface ICC_AudioEncoder;
    interface ICC_StreamProcessor;
	interface ICC_ByteStreamProducer;
    interface ICC_AudioConsumer;
  };                              

  [uuid(dd0b84e0-8c97-48a9-bf32-d58d277b8d53)]
  coclass CC_LPCM_AudioEncoderSettings
  {
    [default]
    interface ICC_LPCM_AudioEncoderSettings;
    interface ICC_LPCM_AudioStreamInfo;
  };

  [uuid(6232dc00-73aa-46f6-bc40-4293737bb11f)]
  coclass CC_HLS_Multiplexer
  {
    [default]
    interface ICC_Multiplexer;
    interface ICC_StreamProcessor;
    interface ICC_ByteStreamProducer;
  }

  [uuid(e33e35bc-e11f-4d77-96a0-480a768eee3d)]
  coclass CC_HLS_MultiplexerSettings
  {
    [default]
    interface ICC_HLS_MultiplexerSettings;
  }

  [uuid(095e2bed-9610-4550-9505-b4d0a3198511)]
  coclass CC_J2K_VideoSplitter
  {
    [default]
	interface ICC_J2K_VideoSplitter;
    interface ICC_Transcoder;
    interface ICC_Splitter;
	interface ICC_VideoSplitter;
    interface ICC_StreamProcessor;
	interface ICC_ByteStreamConsumer;
    interface ICC_ByteStreamProducer;
    interface ICC_TimeBaseProp;
  };

  [uuid(c8069cc9-67bf-40cd-a78c-69652ee17f34)]
  coclass CC_J2K_VideoDecoder
  {
    [default]
	interface ICC_J2K_VideoDecoder;
	interface ICC_VideoDecoder;
    interface ICC_StreamProcessor;
	interface ICC_ByteStreamConsumer;
    interface ICC_VideoProducer;
    interface ICC_VideoProducerExt;
	interface ICC_ThreadsAffinityProp;
	interface ICC_ThreadsPriorityProp;
    interface ICC_ThreadsCountProp;
    interface ICC_TimeBaseProp;
    interface ICC_InputBufferControl;
  };

  [uuid(8c1e236a-2602-41b2-89b0-97810070a089)]
  coclass CC_SonyRaw_VideoDecoder
  {
    [default]
	interface ICC_SonyRaw_VideoDecoder;
	interface ICC_VideoDecoder;
    interface ICC_StreamProcessor;
	interface ICC_ByteStreamConsumer;
    interface ICC_VideoProducer;
    interface ICC_VideoProducerExt;
	interface ICC_ThreadsAffinityProp;
	interface ICC_ThreadsPriorityProp;
    interface ICC_ThreadsCountProp;
    interface ICC_TimeBaseProp;
    interface ICC_InputBufferControl;
  };

  [uuid(76bef61e-f17d-4079-8f22-0c18fbf38e65)]
  coclass CC_DanielVideoSplitter
  {
    [default]
	interface ICC_DanielVideoSplitter;
    interface ICC_Transcoder;
    interface ICC_Splitter;
	interface ICC_VideoSplitter;
    interface ICC_StreamProcessor;
	interface ICC_ByteStreamConsumer;
    interface ICC_ByteStreamProducer;
    interface ICC_TimeBaseProp;
  };

  [uuid(0236cdb4-3541-4c66-a211-496e91922dba)]
  coclass CC_DanielVideoDecoder
  {
    [default]
	interface ICC_DanielVideoDecoder;
	interface ICC_VideoDecoder;
    interface ICC_StreamProcessor;
	interface ICC_ByteStreamConsumer;
    interface ICC_VideoProducer;
    interface ICC_VideoProducerExt;
	interface ICC_ThreadsAffinityProp;
	interface ICC_ThreadsPriorityProp;
    interface ICC_ThreadsCountProp;
    interface ICC_TimeBaseProp;
    interface ICC_InputBufferControl;
  };

  [uuid(00a25ffa-f7bf-4876-a592-73f944936a6f)]
  coclass CC_DanielVideoDecoder_CUDA
  {
    [default]
	interface ICC_DanielVideoDecoder;
	interface ICC_VideoDecoder;
    interface ICC_StreamProcessor;
	interface ICC_ByteStreamConsumer;
    interface ICC_VideoProducer;
    interface ICC_VideoProducerExt;
	interface ICC_ThreadsAffinityProp;
	interface ICC_ThreadsPriorityProp;
    interface ICC_ThreadsCountProp;
    interface ICC_TimeBaseProp;
    interface ICC_InputBufferControl;
    interface ICC_D2D_GetUpdateVideoBufferPtrProp;
  };

  [uuid(942d0694-04ec-4995-b4af-85869f5c605e)]
  coclass CC_DanielVideoDecoder_CudaPlayer
  {
    [default]
	interface ICC_DanielVideoDecoder_CudaPlayer;
    interface ICC_StreamProcessor;
	interface ICC_ByteStreamConsumer;
    interface ICC_TimeBaseProp;
  };

  [uuid(5fd43ca9-0f0f-40e0-a20a-74c9a5edbec8)]
  coclass CC_DanielVideoEncoder
  {
    [default]
	interface ICC_DanielVideoEncoder;
	interface ICC_VideoEncoder;
    interface ICC_StreamProcessor;
	interface ICC_ByteStreamProducer;
    interface ICC_VideoConsumer;
    interface ICC_VideoConsumerExt;
	interface ICC_ThreadsAffinityProp;
	interface ICC_ThreadsPriorityProp;
    interface ICC_ThreadsCountProp;
    interface ICC_TimeBaseProp;
    interface ICC_InputBufferControl;
  };

  [uuid(6e0bf254-f734-4d75-ab2f-de598be15616)]
  coclass CC_DanielVideoEncoder_CUDA
  {
    [default]
	interface ICC_DanielVideoEncoder;
	interface ICC_VideoEncoder;
    interface ICC_StreamProcessor;
	interface ICC_ByteStreamProducer;
    interface ICC_VideoConsumer;
    interface ICC_VideoConsumerExt;
	interface ICC_ThreadsPriorityProp;
    interface ICC_TimeBaseProp;
    interface ICC_InputBufferControl;
  };

  [uuid(fd5a7ff2-a1fe-41af-b27a-0d786a738473)]
  coclass CC_DanielVideoEncoderSettings
  {
    [default]
    interface ICC_DanielVideoEncoderSettings;
  };

  [uuid(2faf33b7-bb91-401b-82de-363e3cd5d309)]
  coclass CC_DanielVideoEncoderSettings_CUDA
  {
    [default]
    interface ICC_DanielVideoEncoderSettings;
  };

  [uuid(331cbbb5-6dd6-4bcb-92ae-037df25fe92e)]
  coclass CC_MediaReader
  {
    [default]
    interface ICC_MediaReader;
  };

  [uuid(1d200482-6ddc-420a-8a6c-255702911ae7)]
  coclass CC_InputFile
  {
    [default]
    interface ICC_File;
    interface ICC_InputStream;
    interface ICC_DataReader;
    interface ICC_DataReaderEx;
    interface ICC_StreamPositionProp;
    interface ICC_StreamLengthProp;
  };

  [uuid(3b0a99b4-809c-4a6e-be17-90814953e708)]
  coclass CC_OutputFile
  {
    [default]
    interface ICC_File;
    interface ICC_DataWriter;
    interface ICC_DataWriterEx;
    interface ICC_StreamPositionProp;
    interface ICC_StreamLengthProp;
	interface ICC_ByteStreamConsumer;
	interface ICC_ByteStreamCallback;
	interface ICC_Breakable;
  };

  [uuid(bda1912f-7051-47fe-883f-6cd42af55085)]
  coclass CC_WavAudioEncoder
  {
    [default]
	interface ICC_WavAudioEncoder;
	interface ICC_StreamProcessor;
	interface ICC_AudioConsumer;
  };

  [uuid(ad9b9cfb-0644-4cce-859c-4aee1ec4f748)]
  coclass CC_WavAudioEncoderSettings
  {
    [default]
    interface ICC_WavAudioEncoderSettings;
    interface ICC_WavAudioStreamInfo;
  };

  [uuid(0d9505f9-f31a-4351-bb39-d369950439a9)]
  coclass CC_HEVCVideoEncoder
  {
    [default]
    interface ICC_HEVCVideoEncoder;
    interface ICC_VideoEncoder;
    interface ICC_VideoConsumer;
    interface ICC_VideoConsumerExt;
    interface ICC_ByteStreamProducer;
    interface ICC_StreamProcessor;
    interface ICC_InputBufferControl;
    interface ICC_TimeBaseProp;
    interface ICC_AddUserDataCtrl;
  };

  [uuid(c7e8a86e-e4f8-4865-a313-b1dcb64b86cd)]
  coclass CC_HEVCVideoEncoderSettings
  {
    [default]
    interface ICC_HEVCVideoEncoderSettings;
  };

  [uuid(e53dc514-51cc-4844-b17e-edfa0ee32c17)]
  coclass CC_HEVCVideoSplitter
  {
    [default]
    interface ICC_HEVCVideoSplitter;
    interface ICC_Splitter;
    interface ICC_Transcoder;
	interface ICC_ByteStreamProducer;
	interface ICC_ByteStreamConsumer;
    interface ICC_StreamProcessor;
    interface ICC_TimeBaseProp;
  };

  [uuid(4013d46c-ce5f-4e6c-949b-0a872f575b59)]
  coclass CC_HEVCVideoDecoder
  {
    [default]
    interface ICC_HEVCVideoDecoder;
    interface ICC_VideoDecoder;
    interface ICC_VideoProducer;
    interface ICC_ByteStreamConsumer;
    interface ICC_ByteStreamCallback;
    interface ICC_StreamProcessor;
    interface ICC_Breakable;
    interface ICC_TimeBaseProp;
  };

  [uuid(d4ce1c4f-60d6-442d-b2bb-45b5d5c6de9b)]
  coclass CC_HEVCVideoDecoder0
  {
    [default]
    interface ICC_HEVCVideoDecoder;
    interface ICC_VideoDecoder;
    interface ICC_VideoProducer;
    interface ICC_ByteStreamConsumer;
    interface ICC_ByteStreamCallback;
    interface ICC_StreamProcessor;
    interface ICC_Breakable;
    interface ICC_TimeBaseProp;
  };

  [uuid(6c6e79c1-d644-4d66-884d-7e9d9b0bbbda)]
  coclass CC_Y4M_VideoEncoder
  {
    [default]
	interface ICC_Y4M_VideoEncoder;
	interface ICC_VideoEncoder;
    interface ICC_StreamProcessor;
	interface ICC_ByteStreamProducer;
    interface ICC_VideoConsumer;
    interface ICC_VideoConsumerExt;
    interface ICC_TimeBaseProp;
  };

  [uuid(bc7a18e4-14eb-485d-bc43-c8932d250970)]
  coclass CC_Y4M_VideoEncoderSettings
  {
    [default]
    interface ICC_Y4M_VideoEncoderSettings;
  };
};

cpp_quote("#ifdef __cplusplus")
cpp_quote("using namespace cinecoder;")
cpp_quote("#endif")
