/* Copyright 2017 Cinegy GmbH.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.

  The version of Cinecoder for these headers should be: 3.28.23.12518
*/

[object, uuid(fe1c44c6-f691-4ee9-b640-70f48defb600), pointer_default(unique), local]
// Represents the WAV-specific audio stream description.
interface ICC_WavAudioStreamInfo : ICC_AudioStreamInfo
{
};

[object, uuid(7fbfb34a-7005-479d-96b5-25a901496c26), pointer_default(unique), local]
// The settings for CC_WavAudioEncoder initialization.
interface ICC_WavAudioEncoderSettings : ICC_LPCM_AudioEncoderSettings
{                        
  
};

// The main interface to access the CC_WavAudioEncoder class.
[object, uuid(92366695-3047-4744-aa87-8d939c6e8a69), pointer_default(unique), local]
interface ICC_WavAudioEncoder : ICC_AudioEncoder
{
};
