/* Copyright 2017 Cinegy GmbH.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.

  The version of Cinecoder for these headers should be: 3.27.39.11441
*/

typedef [v1_enum] enum CC_AAC_FORMAT
{
  CC_AAC_FMT_ADTS			= 0,        /// ADTS (Audio Data Transport Stream) streams have headers for each raw data block, thus making it more suitable for streaming.
  CC_AAC_FMT_ADIF			= 1,        /// ADIF (Audio Data Interchange Format) streams have the header at the beginnig only.
  CC_AAC_FMT_RAW            = 2,        /// No headers, raw data blocks only.
  CC_AAC_FMT_LATM           = 3,        /// MPEG-4 14496-3 stream type
}
CC_AAC_FORMAT;

/// AAC Profiles
typedef [v1_enum] enum CC_AAC_PROFILE
{
  CC_AAC_PROFILE_UNKNOWN 	= 0,        /// Unknown.
  CC_AAC_PROFILE_MAIN 		= 1,        /// Main Profile.
  CC_AAC_PROFILE_LC			= 2,        /// Low Complexity Profile.
  CC_AAC_PROFILE_SSR		= 3,        /// Scalable Sampling Rate Profile.
  CC_AAC_PROFILE_LTP		= 4,        /// Long Term Predictor Profile.
  CC_AAC_PROFILE_SBR 		=16,        /// +Spectral Band Replication
  CC_AAC_PROFILE_PS 		=32,        /// +Parametric Stereo

  CC_AAC_PROFILE_HE         = CC_AAC_PROFILE_LC | CC_AAC_PROFILE_SBR,
  CC_AAC_PROFILE_HE2        = CC_AAC_PROFILE_LC | CC_AAC_PROFILE_SBR | CC_AAC_PROFILE_PS,
}
CC_AAC_PROFILE;

[object, uuid(8d85d96b-1359-4173-99f1-d940420426cc), pointer_default(unique), local]
// Represents the AAC-specified video stream description.
interface ICC_AAC_AudioStreamInfo : ICC_AudioStreamInfo
{
  // AAC format.
  [propget] HRESULT  Format          ([out,retval] CC_AAC_FORMAT      *p);
  // AAC profile.
  [propget] HRESULT  Profile         ([out,retval] CC_AAC_PROFILE     *p);
};

[object, uuid(a212acd4-c2d2-45ed-856f-0cae23f14352), pointer_default(unique), local]
// The information about a particular AAC audio frame.
interface ICC_AAC_AudioFrameInfo : ICC_AudioFrameInfo
{                        
};

[object, uuid(c48df702-21a4-454d-bcb6-28cb0e1c369f), pointer_default(unique), local]
// The settings to specify the AAC stream parameters (may be used for both decoder and encoder)
interface ICC_AAC_AudioStreamSettings : ICC_Settings
{                        
  // AAC format.
  [propget] HRESULT  Format          ([out,retval] CC_AAC_FORMAT      *p);
  [propput] HRESULT  Format          ([in]         CC_AAC_FORMAT       v);
  // AAC profile.
  [propget] HRESULT  Profile         ([out,retval] CC_AAC_PROFILE     *p);
  [propput] HRESULT  Profile         ([in]         CC_AAC_PROFILE      v);
  // The audio sample rate.
  [propget] HRESULT  SampleRate      ([out,retval] CC_UINT            *p);
  [propput] HRESULT  SampleRate      ([in]         CC_UINT             v);
  // The number of audio channels.
  [propget] HRESULT	 NumChannels     ([out,retval] CC_UINT            *p);
  [propput] HRESULT	 NumChannels     ([in]         CC_UINT             v);
  // Destination bitrate.
  [propget] HRESULT  BitRate         ([out,retval] CC_BITRATE         *p);
  [propput] HRESULT  BitRate         ([in]         CC_BITRATE          v);
};

[object, uuid(393e9fcf-eed3-4e74-86d1-2ce034bc680c), pointer_default(unique), local]
// The settings for the CinecoderMpegAudioEncoder initialization.
interface ICC_AAC_AudioEncoderSettings : ICC_AAC_AudioStreamSettings
{                        
};

// The main interface to access the CC_AAC_AudioDecoder class.
[object, uuid(461528f1-d3d3-4349-b728-c5a27ed9afdc), pointer_default(unique), local]
interface ICC_AAC_AudioDecoder : ICC_AudioDecoder
{
};

// The main interface to access the CC_AAC_AudioEncoder class.
[object, uuid(b0fb4156-bb6a-4000-b3c5-c75c93f607a7), pointer_default(unique), local]
interface ICC_AAC_AudioEncoder : ICC_AudioEncoder
{
};

// The main interface for CC_AAC_Parser class
[object, uuid(0d395265-fdf2-4c5d-b63e-c14e597f5e74), pointer_default(unique), local]
interface ICC_AAC_AudioSplitter : ICC_AudioSplitter
{
};

// The class for decoding AAC audio in LATM format
[object, uuid(94f6f31b-cb5d-4813-9c1e-3e047478d063), pointer_default(unique), local]
interface ICC_LATM_AAC_AudioDecoder : ICC_AudioDecoder
{
};

