/* Copyright 2017 Cinegy GmbH.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.

  The version of Cinecoder for these headers should be: 3.30.18.13164
*/

[object, uuid(6a7d55ae-19f4-46e8-87c9-27d95712e966), pointer_default(unique), local]
// Represents the AES3-specified video stream description.
interface ICC_Aes3AudioStreamInfo : ICC_AudioStreamInfo
{
  // The channel number of first data channel - see SMPTE 302M subclause 5.6 for details.
  [propget] HRESULT  ChannelID       ([out,retval] CC_BYTE       *p);
};

[object, uuid(0aac0e66-5eb9-4f8e-9888-8dc511ffa669), pointer_default(unique), local]
// The settings for CC_Aes3AudioEncoder initialization.
interface ICC_Aes3AudioEncoderSettings : ICC_AudioEncoderSettings
{                        
  // The channel number of first data channel - see SMPTE 302M subclause 5.6 for details.
  [propget] HRESULT  ChannelID       ([out,retval] CC_BYTE       *p);
  [propput] HRESULT  ChannelID       ([in]         CC_BYTE        v);

  // The number of audio channels.
  [propget] HRESULT	 NumChannels     ([out,retval] CC_UINT       *p);
  [propput] HRESULT	 NumChannels     ([in]         CC_UINT        v);

  // The quantization of the audio data word. Possible values are 16, 20 or 24.
  [propget] HRESULT  BitsPerSample   ([out,retval] CC_UINT       *p);
  [propput] HRESULT  BitsPerSample   ([in]         CC_UINT        v);

  // The number of audio frames per second.
  [propget] HRESULT  FrameRate       ([out,retval] CC_FRAME_RATE *p);
  [propput] HRESULT  FrameRate       ([in]         CC_FRAME_RATE  v);
};

[object, uuid(30f5700b-dd51-4266-b99e-0a6283adf485), pointer_default(unique), local]
// The description of a particular AES3 frame.
interface ICC_Aes3AudioFrameInfo : ICC_AudioFrameInfo
{                        
};

// The main interface to access the CC_Aes3AudioDecoder class.
[object, uuid(9d054d64-c980-4108-918c-3496373314fc), pointer_default(unique), local]
interface ICC_Aes3AudioDecoder : ICC_AudioDecoder
{
};

// The main interface to access the CC_Aes3AudioEncoder class.
[object, uuid(17a5ca65-d735-4e22-a2f9-2971cee7e81e), pointer_default(unique), local]
interface ICC_Aes3AudioEncoder : ICC_AudioEncoder
{
};

