/* Copyright 2017 Cinegy GmbH.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.

  The version of Cinecoder for these headers should be: 3.30.18.13164
*/

[object, uuid(5ad9b3a9-9a15-44ed-9341-7115670e7c77), pointer_default(unique), local]
interface ICC_Y4M_VideoStreamInfo : ICC_VideoStreamInfo
{
};

[object, uuid(43e44fc2-99d9-4e78-aa60-247df8293231), pointer_default(unique), local]
interface ICC_Y4M_VideoFrameInfo : ICC_VideoFrameInfo
{
};

[object, uuid(876b52d4-d01c-49e2-98d7-7449d4989cbb), pointer_default(unique), local]
interface ICC_Y4M_VideoSplitter : ICC_VideoSplitter
{
};

[object, uuid(569d8d00-59e0-440b-8304-fcc356135f9e), pointer_default(unique), local]
interface ICC_Y4M_VideoDecoder : ICC_VideoDecoder
{
};

[object, uuid(bc708f85-7200-4056-80d1-93628c65e5f6), pointer_default(unique), local]
interface ICC_Y4M_VideoEncoderSettings : ICC_Settings
{
  // The physical frame size, in pixels.                               
  [propget] HRESULT  FrameSize                ([out,retval] CC_SIZE*x); 
  [propput] HRESULT  FrameSize                ([in]         CC_SIZE x); 
  // The frame's rate of video stream.                                          
  [propget] HRESULT  FrameRate                ([out,retval] CC_FRAME_RATE*x); 
  [propput] HRESULT  FrameRate                ([in]         CC_FRAME_RATE x); 
  // The field order video.
  [propget] HRESULT  InterlaceType            ([out,retval] CC_INTERLACE_TYPE*); 
  [propput] HRESULT  InterlaceType            ([in]         CC_INTERLACE_TYPE ); 
  // The aspect ratio cx:cy.
  [propget] HRESULT  AspectRatio              ([out,retval] CC_RATIONAL*);
  [propput] HRESULT  AspectRatio              ([in]         CC_RATIONAL );
  // The chroma resolution format (4:2:0, 4:2:2 or 4:4:4).
  [propget] HRESULT  ChromaFormat             ([out,retval] CC_CHROMA_FORMAT*); 
  [propput] HRESULT  ChromaFormat             ([in]         CC_CHROMA_FORMAT );
  // The bit depth of color samples
  [propget] HRESULT  BitDepth                 ([out,retval] DWORD*); 
  [propput] HRESULT  BitDepth                 ([in]         DWORD );
};

[object, uuid(c753bffb-f306-44b4-b164-ec2f1939eec9), pointer_default(unique), local]
interface ICC_Y4M_VideoEncoder : ICC_VideoEncoder
{
};
