/* Copyright 2017 Cinegy GmbH.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.

  The version of Cinecoder for these headers should be: 3.30.18.13164
*/

[object, uuid(abfb14e8-4aa5-40b3-8fc7-c8dc227a62c9), pointer_default(unique), local]
interface ICC_J2K_VideoStreamInfo : ICC_VideoStreamInfo
{
};

[object, uuid(23c787fa-1d2d-436c-95dc-264f1806e557), pointer_default(unique), local]
interface ICC_J2K_VideoFrameInfo : ICC_VideoFrameInfo
{
};

[object, uuid(f341b209-d017-40a7-b9a1-2682d08ae123), pointer_default(unique), local]
interface ICC_J2K_VideoSplitter : ICC_VideoSplitter
{
};

[object, uuid(1c4dfcfd-6afc-471d-bd09-65b2a4bd9a13), pointer_default(unique), local]
interface ICC_J2K_VideoDecoder : ICC_VideoDecoder
{
  // The number of "single" decoders running in parallel
  [propget] HRESULT   ConcurrencyLevel([out,retval] CC_AMOUNT *p);
  [propput] HRESULT   ConcurrencyLevel([in]         CC_AMOUNT  v);
};
