typedef[v1_enum] enum CC_PRORES_TYPE
{
	CC_PRORES_TYPE_UNKNOWN = 0,
	CC_PRORES_422_HQ,
	CC_PRORES_422,
	CC_PRORES_422_LT,
	CC_PRORES_422_PROXY,
	CC_PRORES_4444,
	CC_PRORES_4444_XQ,

} CC_PRORES_TYPE;
