/* Copyright 2017 Cinegy GmbH.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.

  The version of Cinecoder for these headers should be: 3.27.39.11441
*/

[object, uuid(63ebe1fe-888a-468e-9e07-c7c61da1e39b), pointer_default(unique), local]
interface ICC_Mpeg4VideoStreamInfo : ICC_VideoStreamInfo
{
};

[object, uuid(df8c0ede-b2ea-41d4-a447-83364a377e47), pointer_default(unique), local]
interface ICC_Mpeg4VideoFrameInfo : ICC_VideoFrameInfo
{
};

[object, uuid(31c651b2-bfa1-41e8-b7e6-fe1f99d280cd), pointer_default(unique), local]
interface ICC_Mpeg4VideoDecoder : ICC_VideoDecoder
{
};
